#!/usr/bin/env python3
"""
Weather Panel Configuration Manager
Helper script for configuring ESP32 Weather Satellite Clock
"""

import json
import argparse
from pathlib import Path

# Default configuration for ESP32-S3-Touch-LCD-3.49
DEFAULT_CONFIG = {
    "board": {
        "fqbn": "esp32:esp32:esp32s3",
        "name": "ESP32-S3-Touch-LCD-3.49",
        "manufacturer": "WaveShare",
        "processor": "ESP32-S3R8",
        "flash_size": "16MB",
        "psram_size": "8MB",
        "psram_type": "octal",
        "partition_scheme": "huge_app"
    },
    "display": {
        "controller": "AXS15231B",
        "resolution": {
            "width": 172,
            "height": 640
        },
        "interface": "QSPI",
        "rotation": 180,
        "ips": False,
        "orientation": "portrait"
    },
    "qspi_pins": {
        "cs": 45,
        "sck": 47,
        "d0": 39,
        "d1": 48,
        "d2": 40,
        "d3": 21
    },
    "touch": {
        "interface": "I2C",
        "sda": 4,
        "scl": 8,
        "int": 1,
        "address": 72
    },
    "sdmmc": {
        "cs": 38,
        "mosi": 39,
        "sck": 41,
        "miso": 40,
        "mode": 1
    },
    "backlight": {
        "pin": 46,
        "pwm_channel": 0
    },
    "network": {
        "ssid": "YourAP",
        "password": "PleaseInputYourPasswordHere",
        "ntp_server": "pool.ntp.org",
        "gmt_offset_hours": 8
    },
    "satellite_source": "NMC_CN",
    "satellite_config": {
        "nmc_cn": {
            "url_template": "https://image.nmc.cn/product/%d/%02d/%02d/WXBL/medium/SEVP_NSMC_WXBL_FY4B_ETCC_ACHN_LNO_PY_%d%02d%02d%02d%02d00000.JPG",
            "delay_minutes": 45,
            "update_interval_minutes": 15,
            "time_lapse_hours": 8
        }
    },
    "logging": {
        "serial_baud": 115200,
        "debug_output": True
    },
    "power": {
        "sleep_enabled": False,
        "deep_sleep": False
    }
}

def load_config(config_path=None):
    """Load configuration from file or use defaults"""
    if config_path and Path(config_path).exists():
        with open(config_path, 'r') as f:
            return json.load(f)
    return DEFAULT_CONFIG.copy()

def save_config(config, output_path):
    """Save configuration to file"""
    with open(output_path, 'w') as f:
        json.dump(config, f, indent=2)

def validate_config(config):
    """Validate configuration for correctness"""
    errors = []

    # Check board configuration
    if config.get('board', {}).get('fqbn') != 'esp32:esp32:esp32s3':
        errors.append("Board FQBN should be esp32:esp32:esp32s3 for ESP32-S3-Touch-LCD-3.49")

    # Check display resolution
    display = config.get('display', {})
    if display.get('resolution', {}).get('width') != 172:
        errors.append("Display width should be 172 for AXS15231B")
    if display.get('resolution', {}).get('height') != 640:
        errors.append("Display height should be 640 for AXS15231B")

    # Check QSPI pins
    qspi = config.get('qspi_pins', {})
    required_qspi = ['cs', 'sck', 'd0', 'd1', 'd2', 'd3']
    for pin in required_qspi:
        if pin not in qspi:
            errors.append(f"QSPI pin '{pin}' is missing")

    # Check network settings
    network = config.get('network', {})
    if not network.get('ssid'):
        errors.append("WiFi SSID is not configured")
    if not network.get('password'):
        errors.append("WiFi password is not configured")

    return errors

def generate_config_h(config, output_path):
    """Generate Config.h from configuration"""
    network = config.get('network', {})
    qspi = config.get('qspi_pins', {})
    display = config.get('display', {})
    sdmmc = config.get('sdmmc', {})
    backlight = config.get('backlight', {})

    content = f'''// Configuration for Weather Satellite Image Clock
// Target: ESP32-S3-Touch-LCD-3.49 with AXS15231B display
// Generated by Weather Panel Configuration Manager

#ifndef CONFIG_H
#define CONFIG_H

// WiFi Configuration
#define SSID_NAME "{network.get('ssid', 'YourAP')}"
#define SSID_PASSWORD "{network.get('password', 'YourPassword')}"

// Timezone Configuration
#define GMT_OFFSET_SEC ({network.get('gmt_offset_hours', 8)} * 60 * 60)

// Display Configuration
// AXS15231B with {display.get('resolution', {}).get('width', 172)}x{display.get('resolution', {}).get('height', 640)} resolution
#define GFX_BL {backlight.get('pin', 46)}  // Backlight control pin

// QSPI Display Interface Pins for ESP32-S3
#define QSPI_CS   {qspi.get('cs', 45)}  // Chip Select
#define QSPI_SCK  {qspi.get('sck', 47)}  // Clock
#define QSPI_D0   {qspi.get('d0', 39)}  // Data 0 (MOSI)
#define QSPI_D1   {qspi.get('d1', 48)}  // Data 1 (Quad Write)
#define QSPI_D2   {qspi.get('d2', 40)}  // Data 2 (Quad Hold)
#define QSPI_D3   {qspi.get('d3', 21)}  // Data 3 (Quad Read)

// Touch Interface (I2C) - Optional
#define TOUCH_SDA  {config.get('touch', {}).get('sda', 4)}
#define TOUCH_SCL  {config.get('touch', {}).get('scl', 8)}
#define TOUCH_INT  {config.get('touch', {}).get('int', 1)}
#define TOUCH_ADDR {config.get('touch', {}).get('address', 72)}

// SDMMC Card Interface Pins
#define SD_CS    {sdmmc.get('cs', 38)}
#define SD_MOSI  {sdmmc.get('mosi', 39)}
#define SD_SCK   {sdmmc.get('sck', 41)}
#define SD_MISO  {sdmmc.get('miso', 40)}

// Satellite Image Configuration
// Using NMC (National Meteorological Center, China) as source
// Uncomment desired source (only one at a time):
#include "https_nmc_cn.h"
// #include "https_met_ie.h"

// JPEG Decoder Configuration
#define JPEG_BUFFER_SIZE 4096

// Debug Configuration
#define SERIAL_BAUD {config.get('logging', {}).get('serial_baud', 115200)}
#define DEBUG_OUTPUT {str(config.get('logging', {}).get('debug_output', True)).lower()}

// Display Settings
#define DISPLAY_WIDTH {display.get('resolution', {}).get('width', 172)}
#define DISPLAY_HEIGHT {display.get('resolution', {}).get('height', 640)}
#define DISPLAY_ROTATION {display.get('rotation', 180)}
#define DISPLAY_IPS {str(display.get('ips', False)).lower()}

// Clock and Date Display
#define DATE_FONT u8g2_font_fub14_tf
#define TIME_FONT u8g2_font_logisoso92_tn
#define DATE_CURSOR_X 12
#define DATE_CURSOR_Y 28
#define TIME_CURSOR_X 4
#define TIME_CURSOR_Y 130

// Color Definitions (RGB565)
#define RGB565_BLACK       0x0000
#define RGB565_WHITE       0xFFFF
#define RGB565_RED         0xF800
#define RGB565_GREEN       0x07E0
#define RGB565_BLUE        0x001F
#define RGB565_NAVY        0x000F
#define RGB565_DARKCYAN    0x081F
#define RGB565_SILVER      0xC618
#define RGB565_GRAY        0x8430
#define RGB565_YELLOW      0xFFE0
#define RGB565_ORANGE      0xFA20
#define RGB565_PURPLE      0x8010
#define RGB565_TEAL        0x0410
#define RGB565_MAROON      0x8000

#endif // CONFIG_H
'''

    with open(output_path, 'w') as f:
        f.write(content)

def main():
    parser = argparse.ArgumentParser(
        description='Weather Panel Configuration Manager'
    )
    parser.add_argument(
        '--config', '-c',
        help='Path to configuration file'
    )
    parser.add_argument(
        '--output', '-o',
        help='Output directory for generated files'
    )
    parser.add_argument(
        '--validate', '-v',
        action='store_true',
        help='Validate configuration'
    )
    parser.add_argument(
        '--generate-config',
        action='store_true',
        help='Generate board_config.json'
    )
    parser.add_argument(
        '--generate-h',
        action='store_true',
        help='Generate Config.h'
    )
    parser.add_argument(
        '--ssid',
        help='WiFi SSID'
    )
    parser.add_argument(
        '--password',
        help='WiFi password'
    )
    parser.add_argument(
        '--timezone',
        type=int,
        default=8,
        help='Timezone offset in hours (default: 8)'
    )

    args = parser.parse_args()

    # Load configuration
    config = load_config(args.config)

    # Update from command line arguments
    if args.ssid:
        config['network']['ssid'] = args.ssid
    if args.password:
        config['network']['password'] = args.password
    config['network']['gmt_offset_hours'] = args.timezone

    # Validate if requested
    if args.validate:
        errors = validate_config(config)
        if errors:
            print("Configuration errors:")
            for error in errors:
                print(f"  - {error}")
            return 1
        else:
            print("Configuration is valid!")
            return 0

    # Generate files if requested
    output_dir = Path(args.output) if args.output else Path(__file__).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.generate_config:
        config_path = output_dir / 'board_config.json'
        save_config(config, config_path)
        print(f"Generated: {config_path}")

    if args.generate_h:
        config_h_path = output_dir / 'Config.h'
        generate_config_h(config, config_h_path)
        print(f"Generated: {config_h_path}")

    # Generate both by default if neither specified
    if not args.generate_config and not args.generate_h and not args.validate:
        save_config(config, output_dir / 'board_config.json')
        generate_config_h(config, output_dir / 'Config.h')
        print(f"Generated configuration files in: {output_dir}")

    return 0

if __name__ == '__main__':
    exit(main())
